//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEvent
    {
        public System.DateTime StartDate { get; set; }
        public int Id { get; set; }
        public string Theme { get; set; }
        public string Notes { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool WasNotified { get; set; }
    }
}
